package main

import (
	"net/http"

	"github.com/gin-gonic/gin"

	// Blank import registers the generated spec with swag's global
	// registry so ginSwagger.WrapHandler can serve it. The package
	// itself is produced by `swag init -g cmd/edge/main.go -o ./docs`.
	docs "github.com/jtoye/edge/docs"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// registerDocRoutes wires the OpenAPI spec endpoint (/openapi.json) and the
// interactive Swagger UI (/docs/*) into the provided Gin engine. Both routes
// are intentionally public — partner integrators need to fetch the spec
// without having to first obtain a Keycloak token.
//
// `/openapi.json` is served from the embedded spec (generated by `swag
// init` into docs/docs.go) rather than from disk. This keeps the
// container image's scratch base happy — there's no filesystem path to
// copy into the runtime layer.
//
// `/docs/*any` is the Swagger UI served by swaggo/files + gin-swagger. The
// trailing wildcard is mandatory so the UI can resolve its own assets
// (js, css, images) via relative paths under /docs/.
func registerDocRoutes(r *gin.Engine) {
	// Ensure the default spec name is "swagger" (what gin-swagger
	// expects). swag init sets this automatically in docs.go; the
	// assignment here is defensive in case the generated file is ever
	// hand-edited.
	docs.SwaggerInfo.Title = "J'Toye Edge Gateway API"

	// Serve the raw JSON spec at the canonical OpenAPI path. We read it
	// out of the registered swag Doc instead of the filesystem so the
	// scratch-based Dockerfile doesn't need a docs volume.
	r.GET("/openapi.json", func(c *gin.Context) {
		raw := docs.SwaggerInfo.ReadDoc()
		c.Data(http.StatusOK, "application/json; charset=utf-8", []byte(raw))
	})

	// Swagger UI. gin-swagger's WrapHandler discovers the spec via the
	// registered Doc instance (populated by the blank-import above) and
	// serves a full interactive browser at /docs/index.html.
	r.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Convenience redirects so users who type the bare path land on the
	// canonical UI entry point. Without these both /docs and /docs/ return
	// 404 — gin-swagger only binds /docs/<named-asset>.
	r.GET("/docs", func(c *gin.Context) {
		c.Redirect(http.StatusMovedPermanently, "/docs/index.html")
	})
}
