package uk.jtoye.core.onboarding;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;
import uk.jtoye.core.exception.InvalidStateTransitionException;
import uk.jtoye.core.security.TenantContext;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Pure-Mockito unit proof of the gate-chain registry logic in
 * {@link GateChainRunner}: {@code materialise} idempotency and the
 * {@code runAndRecompute} decision table (GATES_PASSED / GATE_FAILED / nothing)
 * plus the {@code onboarding.auto-approve} consumption. Constructing the runner
 * directly (not via the Spring proxy) runs {@code runAndRecompute} inline so its
 * logic — and its {@link TenantContext} set/clear discipline — can be asserted
 * without a container. End-to-end proof on real Postgres lives in
 * {@code OnboardingSubmitIntegrationTest}.
 */
class GateChainRunnerTest {

    private final VendorOnboardingRepository onboardingRepository = mock(VendorOnboardingRepository.class);
    private final VendorOnboardingGateRepository gateRepository = mock(VendorOnboardingGateRepository.class);
    private final OnboardingProperties onboardingProperties = new OnboardingProperties();
    private final VendorOnboardingService vendorOnboardingService = mock(VendorOnboardingService.class);

    @AfterEach
    void clearTenant() {
        TenantContext.clear();
    }

    private GateChainRunner runner(List<OnboardingGate> gates) {
        return new GateChainRunner(gates, onboardingRepository, gateRepository,
                onboardingProperties, vendorOnboardingService);
    }

    private VendorOnboarding onboardingIn(OnboardingState state, UUID id, UUID tenantId) {
        VendorOnboarding o = new VendorOnboarding();
        o.setTenantId(tenantId);
        o.setStatus(state);
        // id is generated by JPA; reflectively unavailable here, so stub findById to
        // return this instance and drive the id via the stubbed argument instead.
        return o;
    }

    private VendorOnboardingGate gateRow(GateType type, GateStatus status, boolean mandatory) {
        VendorOnboardingGate g = new VendorOnboardingGate();
        g.setGateType(type);
        g.setStatus(status);
        g.setMandatory(mandatory);
        return g;
    }

    @Test
    @DisplayName("materialise inserts one PENDING row per registered gate bean")
    void materialiseInsertsPendingRow() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        VendorOnboarding onboarding = onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId);
        onboarding.setTenantId(tenantId);

        OnboardingGate gate = mock(OnboardingGate.class);
        when(gate.type()).thenReturn(GateType.BUSINESS_VERIFIED);
        when(gate.mandatory()).thenReturn(true);
        when(gateRepository.findByOnboardingIdAndGateType(any(), eq(GateType.BUSINESS_VERIFIED)))
                .thenReturn(Optional.empty());

        runner(List.of(gate)).materialise(onboarding);

        ArgumentCaptor<VendorOnboardingGate> captor = ArgumentCaptor.forClass(VendorOnboardingGate.class);
        verify(gateRepository).save(captor.capture());
        VendorOnboardingGate saved = captor.getValue();
        assertThat(saved.getGateType()).isEqualTo(GateType.BUSINESS_VERIFIED);
        assertThat(saved.getStatus()).isEqualTo(GateStatus.PENDING);
        assertThat(saved.isMandatory()).isTrue();
        assertThat(saved.getTenantId()).isEqualTo(tenantId);
    }

    @Test
    @DisplayName("materialise skips a gate type that already has a row")
    void materialiseSkipsExistingRow() {
        VendorOnboarding onboarding = onboardingIn(OnboardingState.VERIFYING, UUID.randomUUID(), UUID.randomUUID());
        OnboardingGate gate = mock(OnboardingGate.class);
        when(gate.type()).thenReturn(GateType.BUSINESS_VERIFIED);
        when(gateRepository.findByOnboardingIdAndGateType(any(), eq(GateType.BUSINESS_VERIFIED)))
                .thenReturn(Optional.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PENDING, true)));

        runner(List.of(gate)).materialise(onboarding);

        verify(gateRepository, never()).save(any());
    }

    @Test
    @DisplayName("materialise with zero gate beans inserts nothing")
    void materialiseWithNoGatesInsertsNothing() {
        VendorOnboarding onboarding = onboardingIn(OnboardingState.VERIFYING, UUID.randomUUID(), UUID.randomUUID());
        runner(List.of()).materialise(onboarding);
        verify(gateRepository, never()).save(any());
    }

    @Test
    @DisplayName("runAndRecompute fires GATES_PASSED (not APPROVE) when all mandatory gates pass and auto-approve is off")
    void recomputeFiresGatesPassedOnly() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        onboardingProperties.setAutoApprove(false);
        when(onboardingRepository.findById(onboardingId))
                .thenReturn(Optional.of(onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId)));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PASSED, true)));

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATES_PASSED);
        verify(vendorOnboardingService, never()).transition(onboardingId, OnboardingEvent.APPROVE);
        assertThat(TenantContext.get()).isEmpty(); // cleared in finally
    }

    @Test
    @DisplayName("runAndRecompute auto-approves WHITE_LABEL on green gates even with global auto-approve off (#178)")
    void recomputeAutoApprovesWhiteLabelByModel() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        onboardingProperties.setAutoApprove(false); // global force-on OFF: per-model policy applies
        VendorOnboarding onboarding = onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId);
        onboarding.setModel(OnboardingModel.WHITE_LABEL);
        when(onboardingRepository.findById(onboardingId)).thenReturn(Optional.of(onboarding));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PASSED, true)));

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATES_PASSED);
        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.APPROVE);
    }

    @Test
    @DisplayName("runAndRecompute halts MARKETPLACE at PENDING_APPROVAL with global auto-approve off (#178)")
    void recomputeHaltsMarketplaceByModel() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        onboardingProperties.setAutoApprove(false); // MARKETPLACE not in the default auto-approve list
        VendorOnboarding onboarding = onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId);
        onboarding.setModel(OnboardingModel.MARKETPLACE);
        when(onboardingRepository.findById(onboardingId)).thenReturn(Optional.of(onboarding));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PASSED, true)));

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATES_PASSED);
        verify(vendorOnboardingService, never()).transition(onboardingId, OnboardingEvent.APPROVE);
    }

    @Test
    @DisplayName("runAndRecompute also fires APPROVE when auto-approve is on")
    void recomputeAutoApproves() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        onboardingProperties.setAutoApprove(true);
        when(onboardingRepository.findById(onboardingId))
                .thenReturn(Optional.of(onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId)));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PASSED, true)));

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATES_PASSED);
        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.APPROVE);
    }

    @Test
    @DisplayName("runAndRecompute swallows a vetoed auto-APPROVE and keeps GATES_PASSED (WR-01)")
    void recomputeSwallowsVetoedAutoApprove() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        onboardingProperties.setAutoApprove(true);
        when(onboardingRepository.findById(onboardingId))
                .thenReturn(Optional.of(onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId)));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.PASSED, true)));
        // The APPROVE guard vetoes -> InvalidStateTransitionException. WR-01: it must
        // NOT abort the run (which would roll back the committed gate evaluations and
        // the already-fired GATES_PASSED, re-stranding the onboarding in VERIFYING).
        doThrow(new InvalidStateTransitionException("vetoed"))
                .when(vendorOnboardingService).transition(onboardingId, OnboardingEvent.APPROVE);

        GateChainRunner runner = runner(List.of());
        assertThatCode(() -> runner.runAndRecompute(onboardingId, tenantId))
                .doesNotThrowAnyException();

        // GATES_PASSED still fired (progress preserved); the veto was caught, not propagated.
        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATES_PASSED);
        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.APPROVE);
        assertThat(TenantContext.get()).isEmpty(); // finally still cleared the tenant
    }

    @Test
    @DisplayName("runAndRecompute fires GATE_FAILED when a mandatory gate failed")
    void recomputeFiresGateFailed() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        when(onboardingRepository.findById(onboardingId))
                .thenReturn(Optional.of(onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId)));
        when(gateRepository.findByOnboardingId(onboardingId))
                .thenReturn(List.of(gateRow(GateType.BUSINESS_VERIFIED, GateStatus.FAILED, true)));

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService).transition(onboardingId, OnboardingEvent.GATE_FAILED);
        verify(vendorOnboardingService, never()).transition(onboardingId, OnboardingEvent.GATES_PASSED);
    }

    @Test
    @DisplayName("runAndRecompute with no materialised gate rows fires no transition")
    void recomputeWithNoRowsDoesNothing() {
        UUID onboardingId = UUID.randomUUID();
        UUID tenantId = UUID.randomUUID();
        when(onboardingRepository.findById(onboardingId))
                .thenReturn(Optional.of(onboardingIn(OnboardingState.VERIFYING, onboardingId, tenantId)));
        when(gateRepository.findByOnboardingId(onboardingId)).thenReturn(List.of());

        runner(List.of()).runAndRecompute(onboardingId, tenantId);

        verify(vendorOnboardingService, never()).transition(any(), any());
    }
}
