package uk.jtoye.core.order;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import uk.jtoye.core.testsupport.IntegrationTestSupport;
import uk.jtoye.core.order.dto.CreateOrderRequest;
import uk.jtoye.core.order.dto.OrderDto;
import uk.jtoye.core.order.dto.OrderItemRequest;
import uk.jtoye.core.product.Product;
import uk.jtoye.core.product.ProductRepository;
import uk.jtoye.core.security.TenantContext;
import uk.jtoye.core.shop.Shop;
import uk.jtoye.core.shop.ShopRepository;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for Order management.
 * Tests order CRUD operations and tenant isolation.
 * Requires PostgreSQL via Testcontainers for SET LOCAL tenant context.
 */
@SpringBootTest(properties = {
        "logging.level.uk.jtoye.core.security.TenantSetLocalAspect=DEBUG"
})
@Testcontainers
@ActiveProfiles("test")
@Transactional
@org.junit.jupiter.api.Tag("testcontainers")
class OrderControllerIntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15")
            .withDatabaseName("jtoye_test")
            .withUsername("test")
            .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        IntegrationTestSupport.registerPostgresTestProperties(registry, postgres);
    }

    @Autowired
    private OrderService orderService;

    @Autowired
    private OrderRepository orderRepository;

    @Autowired
    private ShopRepository shopRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private static final UUID TENANT_A = UUID.fromString("00000000-0000-0000-0000-000000000001");
    private static final UUID TENANT_B = UUID.fromString("00000000-0000-0000-0000-000000000002");

    private UUID shopAId;
    private UUID productAId;

    @BeforeEach
    void setUp() {
        // Create tenants
        jdbcTemplate.execute("INSERT INTO tenants (id, name, created_at) VALUES ('" + TENANT_A + "', 'Tenant A', CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING");
        jdbcTemplate.execute("INSERT INTO tenants (id, name, created_at) VALUES ('" + TENANT_B + "', 'Tenant B', CURRENT_TIMESTAMP) ON CONFLICT (id) DO NOTHING");

        // Create shop for Tenant A
        TenantContext.set(TENANT_A);
        Shop shopA = new Shop();
        shopA.setTenantId(TENANT_A);
        shopA.setName("Shop A");
        shopA.setAddress("Address A");
        // shops.slug is NOT NULL UNIQUE and normally generated by ShopService
        shopA.setSlug("it-" + java.util.UUID.randomUUID().toString().substring(0, 8));
        shopA = shopRepository.save(shopA);
        shopAId = shopA.getId();

        // Create product for Tenant A
        Product productA = new Product();
        productA.setTenantId(TENANT_A);
        productA.setSku("SKU-A");
        productA.setTitle("Product A");
        productA.setIngredientsText("Ingredients A");
        productA.setAllergenMask(0);
        productA = productRepository.save(productA);
        productAId = productA.getId();

        TenantContext.clear();
    }

    @Test
    void testCreateOrder() {
        TenantContext.set(TENANT_A);
        try {
            // Create order request
            CreateOrderRequest request = new CreateOrderRequest();
            request.setShopId(shopAId);
            request.setCustomerName("John Doe");
            request.setCustomerEmail("john@example.com");
            request.setCustomerPhone("555-1234");
            request.setNotes("Test order");

            OrderItemRequest item = new OrderItemRequest();
            item.setProductId(productAId);
            item.setQuantity(2);
            request.setItems(List.of(item));

            // Create order
            OrderDto order = orderService.createOrder(request);

            // Verify order created
            assertThat(order).isNotNull();
            assertThat(order.getId()).isNotNull();
            assertThat(order.getTenantId()).isEqualTo(TENANT_A);
            assertThat(order.getShopId()).isEqualTo(shopAId);
            assertThat(order.getOrderNumber()).startsWith("ORD-");
            assertThat(order.getStatus()).isEqualTo(OrderStatus.DRAFT);
            assertThat(order.getCustomerName()).isEqualTo("John Doe");
            assertThat(order.getTotalAmountPennies()).isGreaterThan(0);

        } finally {
            TenantContext.clear();
        }
    }

    @Test
    void testGetOrderById() {
        TenantContext.set(TENANT_A);
        try {
            // Create order
            CreateOrderRequest request = new CreateOrderRequest();
            request.setShopId(shopAId);
            request.setCustomerName("Jane Doe");
            OrderItemRequest item = new OrderItemRequest();
            item.setProductId(productAId);
            item.setQuantity(1);
            request.setItems(List.of(item));

            OrderDto createdOrder = orderService.createOrder(request);

            // Retrieve order
            Optional<OrderDto> retrievedOrder = orderService.getOrderById(createdOrder.getId());

            // Verify
            assertThat(retrievedOrder).isPresent();
            assertThat(retrievedOrder.get().getId()).isEqualTo(createdOrder.getId());
            assertThat(retrievedOrder.get().getCustomerName()).isEqualTo("Jane Doe");

        } finally {
            TenantContext.clear();
        }
    }

    @Test
    void testUpdateOrderStatus() {
        TenantContext.set(TENANT_A);
        try {
            // Create order
            CreateOrderRequest request = new CreateOrderRequest();
            request.setShopId(shopAId);
            OrderItemRequest item = new OrderItemRequest();
            item.setProductId(productAId);
            item.setQuantity(1);
            request.setItems(List.of(item));

            OrderDto createdOrder = orderService.createOrder(request);
            assertThat(createdOrder.getStatus()).isEqualTo(OrderStatus.DRAFT);

            // Update status through the proper state machine path:
            // DRAFT → PENDING → CONFIRMED. The legacy updateOrderStatus() shortcut
            // that bypassed the state machine was removed (see Audit Phase 2, Fix #5).
            orderService.submitOrder(createdOrder.getId());
            OrderDto updatedOrder = orderService.confirmOrder(createdOrder.getId());

            // Verify
            assertThat(updatedOrder.getStatus()).isEqualTo(OrderStatus.CONFIRMED);
            assertThat(updatedOrder.getUpdatedAt()).isAfter(createdOrder.getUpdatedAt());

        } finally {
            TenantContext.clear();
        }
    }

    @Test
    void testGetOrdersByStatus() {
        TenantContext.set(TENANT_A);
        try {
            // Create multiple orders
            for (int i = 0; i < 3; i++) {
                CreateOrderRequest request = new CreateOrderRequest();
                request.setShopId(shopAId);
                OrderItemRequest item = new OrderItemRequest();
                item.setProductId(productAId);
                item.setQuantity(1);
                request.setItems(List.of(item));

                orderService.createOrder(request);
            }

            // Get orders by status (paginated — Issue #95)
            Page<OrderDto> draftOrders = orderService.getOrdersByStatus(
                    OrderStatus.DRAFT, PageRequest.of(0, 20));

            // Verify
            assertThat(draftOrders.getTotalElements()).isGreaterThanOrEqualTo(3);
            assertThat(draftOrders.getContent()).allMatch(o -> o.getStatus() == OrderStatus.DRAFT);
            assertThat(draftOrders.getContent()).allMatch(o -> o.getTenantId().equals(TENANT_A));

        } finally {
            TenantContext.clear();
        }
    }

    /**
     * Issue #95: the formerly-unbounded by-status/by-shop/by-customer list paths
     * must slice correctly against real Postgres (with the RLS tenant GUC applied
     * by TenantSetLocalAspect on every repository call).
     */
    @Test
    void testOrderListPaginationSlicing() {
        TenantContext.set(TENANT_A);
        try {
            UUID customerId = createCustomer("paging@example.com");
            for (int i = 0; i < 3; i++) {
                CreateOrderRequest request = new CreateOrderRequest();
                request.setShopId(shopAId);
                request.setCustomerId(customerId);
                OrderItemRequest item = new OrderItemRequest();
                item.setProductId(productAId);
                item.setQuantity(1);
                request.setItems(List.of(item));
                orderService.createOrder(request);
            }

            Pageable firstPage = PageRequest.of(0, 2, Sort.by(Sort.Direction.DESC, "createdAt"));
            Pageable secondPage = PageRequest.of(1, 2, Sort.by(Sort.Direction.DESC, "createdAt"));

            // By status: 3 orders → page 0 has 2, page 1 has 1
            Page<OrderDto> statusPage0 = orderService.getOrdersByStatus(OrderStatus.DRAFT, firstPage);
            Page<OrderDto> statusPage1 = orderService.getOrdersByStatus(OrderStatus.DRAFT, secondPage);
            assertThat(statusPage0.getContent()).hasSize(2);
            assertThat(statusPage0.getTotalElements()).isEqualTo(3);
            assertThat(statusPage0.getTotalPages()).isEqualTo(2);
            assertThat(statusPage1.getContent()).hasSize(1);

            // By shop
            Page<OrderDto> shopPage0 = orderService.getOrdersByShop(shopAId, firstPage);
            Page<OrderDto> shopPage1 = orderService.getOrdersByShop(shopAId, secondPage);
            assertThat(shopPage0.getContent()).hasSize(2);
            assertThat(shopPage0.getTotalElements()).isEqualTo(3);
            assertThat(shopPage1.getContent()).hasSize(1);

            // By customer
            Page<OrderDto> customerPage0 = orderService.getOrdersByCustomer(customerId, firstPage);
            Page<OrderDto> customerPage1 = orderService.getOrdersByCustomer(customerId, secondPage);
            assertThat(customerPage0.getContent()).hasSize(2);
            assertThat(customerPage0.getTotalElements()).isEqualTo(3);
            assertThat(customerPage1.getContent()).hasSize(1);

            // No page leaks another tenant's rows
            assertThat(statusPage0.getContent()).allMatch(o -> o.getTenantId().equals(TENANT_A));
            assertThat(shopPage0.getContent()).allMatch(o -> o.getTenantId().equals(TENANT_A));
            assertThat(customerPage0.getContent()).allMatch(o -> o.getTenantId().equals(TENANT_A));
        } finally {
            TenantContext.clear();
        }
    }

    private UUID createCustomer(String email) {
        UUID id = UUID.randomUUID();
        jdbcTemplate.update(
                "INSERT INTO customers (id, tenant_id, name, email, created_at, updated_at) "
                        + "VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                id, TENANT_A, "Paging Customer", email);
        return id;
    }

    @Test
    void testTenantIsolation() {
        // Create order for Tenant A
        TenantContext.set(TENANT_A);
        CreateOrderRequest requestA = new CreateOrderRequest();
        requestA.setShopId(shopAId);
        requestA.setCustomerName("Tenant A Customer");
        OrderItemRequest itemA = new OrderItemRequest();
        itemA.setProductId(productAId);
        itemA.setQuantity(1);
        requestA.setItems(List.of(itemA));

        OrderDto orderA = orderService.createOrder(requestA);
        UUID orderAId = orderA.getId();

        // Verify order belongs to Tenant A
        assertThat(orderA.getTenantId()).isEqualTo(TENANT_A);

        // Verify order can be retrieved by Tenant A
        Optional<OrderDto> retrievedA = orderService.getOrderById(orderAId);
        assertThat(retrievedA).isPresent();
        assertThat(retrievedA.get().getTenantId()).isEqualTo(TENANT_A);

        TenantContext.clear();

        // Verify order entity has correct tenant_id column value
        Order order = orderRepository.findById(orderAId).orElse(null);
        assertThat(order).isNotNull();
        assertThat(order.getTenantId()).isEqualTo(TENANT_A);

        // NOTE: Full RLS isolation testing within a single @Transactional test is complex
        // because SET LOCAL persists for the entire transaction. RLS is verified in production
        // where each HTTP request gets its own transaction with the correct tenant context.
        // The tenant_id column checks above ensure data integrity at the database level.
    }

    @Test
    void testDeleteOrder() {
        TenantContext.set(TENANT_A);
        try {
            // Create order
            CreateOrderRequest request = new CreateOrderRequest();
            request.setShopId(shopAId);
            OrderItemRequest item = new OrderItemRequest();
            item.setProductId(productAId);
            item.setQuantity(1);
            request.setItems(List.of(item));

            OrderDto createdOrder = orderService.createOrder(request);
            UUID orderId = createdOrder.getId();

            // Delete order
            orderService.deleteOrder(orderId);

            // Verify deleted
            Optional<OrderDto> result = orderService.getOrderById(orderId);
            assertThat(result).isEmpty();

        } finally {
            TenantContext.clear();
        }
    }
}
