#!/usr/bin/env bash
#
# Gate: the OGL attribution rendered to users must match the postcode dataset actually committed.
#
# OS Code-Point Open ships under the Open Government Licence v3. Commercial use inside a proprietary
# product is permitted and there is no share-alike clause; acknowledgement is the ONE obligation the
# licence imposes. So this is a compliance gate, not a style gate.
#
# It checks two things a year-only check would miss:
#   1. ALL THREE attribution lines render. A footer carrying only the Ordnance Survey line is a
#      breach — Royal Mail and National Statistics are separate rights holders.
#   2. The rendered year equals the year in the committed SOURCE.md. The year is not decorative: it
#      identifies the dataset release, and it must move when the dataset is refreshed. A footer
#      claiming 2026 over a 2027 dataset misattributes it.
#
# Exit codes:
#   0  attribution is correct and matches the committed dataset
#   1  attribution is wrong — a line is missing, or the year has drifted
#   2  VOID — an input is missing, unparseable, or yielded an EMPTY result
#
# 2 is deliberate and load-bearing. "I could not find the footer" must never read as "the footer is
# fine": a gate that fails OPEN on missing input is worse than no gate, because it is trusted.
#
# Shell shapes deliberately avoided, both recorded failure modes in this repo:
#   * `cmd | grep -q X` under `set -o pipefail` INVERTS on match — grep exits at the first hit, the
#     writer takes SIGPIPE, pipefail promotes it to 141. Here-strings only.
#   * `grep -c` exits 1 on a ZERO count, i.e. on the desired state of an absence check. Counts are
#     captured with `|| true` and compared as values.

set -uo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"

SOURCE_MD="$REPO_ROOT/core-java/src/main/resources/geo/SOURCE.md"
FOOTER="$REPO_ROOT/frontend/components/public/public-footer.tsx"

# The three rights holders OGL requires be named. Matched on the distinctive phrase rather than the
# © glyph, because the footer is JSX (`&copy;`) and SOURCE.md is Markdown (`©`) — matching the glyph
# would make this gate a test of entity encoding rather than of licence compliance.
HOLDERS=("Ordnance Survey data" "Royal Mail data" "National Statistics data")

fail() { echo "FAIL: $*" >&2; exit 1; }
void() { echo "VOID: $*" >&2; exit 2; }

echo "Geo attribution gate"
echo "  dataset provenance : ${SOURCE_MD#"$REPO_ROOT"/}"
echo "  rendered surface   : ${FOOTER#"$REPO_ROOT"/}"

# ---- inputs must exist and be readable; anything else is VOID ---------------------------------
[ -f "$SOURCE_MD" ] || void "dataset provenance file not found: $SOURCE_MD"
[ -f "$FOOTER" ]    || void "footer component not found: $FOOTER"
[ -s "$SOURCE_MD" ] || void "dataset provenance file is empty: $SOURCE_MD"
[ -s "$FOOTER" ]    || void "footer component is empty: $FOOTER"

# ---- the dataset's attribution year ------------------------------------------------------------
# SOURCE.md is generated by regen-postcode-centroids.sh and states it on the "Attribution year" row.
DATASET_YEAR="$(sed -n 's/.*Attribution year.*\*\*\([0-9][0-9][0-9][0-9]\)\*\*.*/\1/p' "$SOURCE_MD" | head -1)"
[ -n "$DATASET_YEAR" ] || void "could not parse an attribution year out of $SOURCE_MD"

# ---- the year the footer actually renders ------------------------------------------------------
# Read from the GEO_ATTRIBUTION_YEAR constant. Deliberately NOT from `new Date()`, which is the
# copyright year and moves every January — conflating the two is the drift this gate exists to catch.
FOOTER_YEAR="$(sed -n 's/.*GEO_ATTRIBUTION_YEAR[[:space:]]*=[[:space:]]*"\([0-9][0-9][0-9][0-9]\)".*/\1/p' "$FOOTER" | head -1)"
[ -n "$FOOTER_YEAR" ] || void "could not parse GEO_ATTRIBUTION_YEAR out of $FOOTER"

echo "  dataset year       : $DATASET_YEAR"
echo "  footer year        : $FOOTER_YEAR"

# ---- 1. all three rights holders must be named -------------------------------------------------
missing=()
for holder in "${HOLDERS[@]}"; do
    n="$(grep -cF -- "$holder" "$FOOTER" || true)"
    [ -n "$n" ] || void "attribution count for '$holder' yielded an empty result"
    if [ "$n" -lt 1 ]; then
        missing+=("$holder")
    else
        echo "  attribution        : '$holder' present"
    fi
done
if [ "${#missing[@]}" -gt 0 ]; then
    fail "the footer does not name ${#missing[@]} required rights holder(s): ${missing[*]}. OGL requires all three; shipping a subset is a licence breach."
fi

# ---- 2. the rendered year must match the committed dataset --------------------------------------
if [ "$FOOTER_YEAR" != "$DATASET_YEAR" ]; then
    fail "attribution year drift — the footer renders $FOOTER_YEAR but the committed dataset is $DATASET_YEAR. Regenerate the dataset or correct the footer; do not just make the numbers agree."
fi

# ---- 3. the year must actually appear beside the attribution, not only in the constant ----------
# Guards a footer that keeps GEO_ATTRIBUTION_YEAR but stops rendering it.
used="$(grep -cF -- 'GEO_ATTRIBUTION_YEAR' "$FOOTER" || true)"
[ -n "$used" ] || void "usage count for GEO_ATTRIBUTION_YEAR yielded an empty result"
if [ "$used" -lt 4 ]; then
    fail "GEO_ATTRIBUTION_YEAR appears only $used time(s) in the footer — expected its declaration plus one interpolation per rights holder (4). A declared-but-unrendered constant attributes nothing."
fi

echo "PASS: three attribution lines render and the year matches the committed dataset ($DATASET_YEAR)"
